{
 "title": "Kafka Overview",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Event and Processing Time Latecy (JAVA)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_resellerUsageStatistics_metrics_resellerUsageStatistics_EventTimeLatency",
     "legendFormat": "Event Time Latency"
    },
    {
     "expr": "com_resellerUsageStatistics_metrics_resellerUsageStatistics_ProcessingTimeLatency",
     "legendFormat": "Processing Time Latency"
    }
   ]
  },
  {
   "title": "Event Time latency  vs Processin time ratio (JAVA)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_resellerUsageStatistics_metrics_resellerUsageStatistics_EventTimeLatency/com_resellerUsageStatistics_metrics_resellerUsageStatistics_ProcessingTimeLatency",
     "legendFormat": "Even ProcessingTimeLatency"
    }
   ]
  },
  {
   "title": "Total Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",topic=\"TransactionsTopic\"}[30s]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Total Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic=\"TransactionsTopic\"}[10s]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",topic=\"TransactionsTopic\"}[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic=\"TransactionsTopic\"}[10s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\",topic=\"TransactionsTopic\"}[30s]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages Out Per Topic (JAVA Consumption rate)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(com_resellerUsageStatistics_metrics_resellerUsageStatistics_TotalNumberMessagesIn[10s]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Event and Processing Time Latency (FLINK)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(flink_taskmanager_job_task_operator_EventLatencyGauge)",
     "legendFormat": "Event Time Latency"
    },
    {
     "expr": "avg(flink_taskmanager_job_task_operator_ProcessingLatencyGauge)",
     "legendFormat": "Processing Time latency"
    }
   ]
  },
  {
   "title": "est. Messages Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\",topic=\"TransactionsTopic\"}[10s])/478)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Event Time latency  vs Processin time ratio (FLINK)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(flink_taskmanager_job_task_operator_EventLatencyGauge) / avg(flink_taskmanager_job_task_operator_ProcessingLatencyGauge)"
    },
    {}
   ]
  },
  {
   "title": "Average size of object",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Average Size" }
   ],
   "targets": [
    {
     "expr": "((sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",topic!=\"\"}[30s])))/(sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic!=\"\"}[30s]))))",
     "legendFormat": "size of object in {{topic}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}